### ISSUE TITLE
Improve error reporting

### ISSUE THREAD

**Issue by jkot** [Cascading/lingual#7]
When connecting Lingual to Postgresql using cascading-jdbc, I made a mistake in the JDBC connection string:
jdbc:postgres://localhost:5432/sesame_store  instead of
jdbc:postgresql://localhost:5432/sesame_store

After trying to run a query I got just the following error reports in the shell:

```
Warning: exception while executing query (state=,code=0)
Error: exception while executing query (state=,code=0)
```

It would be nice to see something more informative, it took me quite a long time to debug the problem. I'll do a pull request with a suggested fix after which the message would be the following:

```
Warning: exception while executing query: null: unable to create connection: No suitable driver found for jdbc:postgres://localhost:5432/mydb?user=postgres&password=postgres (state=,code=0)
Error: exception while executing query (state=,code=0)
```

It would perhaps also be nice to mention that one can increase logging by modifying log4j.properties in ~/.lingual-client/lib/lingual-client-1.0.0-wip-???.jar

**Comment by joeposner** [comment]
Thanks for the pull request with the change to logging messages that accompanied this.

As you note the default message is not what a user would want it to be and needs to be changed. But while developing, you can also try running with either "--verbose" or "--showstacktrace" options which provide much more detail about what the system is doing and what errors happened. Both of them show too much detail for regular use which is why they are optional flags.

**Comment by jkot** [comment]
I've tried --verbose but it didn't help me in this case. Somehow I missed --showstacktrace, thanks!

I fixed my change as you wanted - you can see it in the pull request.

**Comment by joeposner** [comment]
This commit was merged two weeks ago and I forgot to mark this issue as closed at the time.

Closing it now.
